/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DeferredDataImport } from './routes/deferred-data'
import { Route as ContactUsImport } from './routes/contact-us'
import { Route as AboutUsImport } from './routes/about-us'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutLayoutBImport } from './routes/_layout.layout-b'
import { Route as LayoutLayoutAImport } from './routes/_layout.layout-a'
import { Route as AuthedDashboardImport } from './routes/_authed/dashboard'
import { Route as stocksStarbucksCorporationImport } from './routes/(stocks)/starbucks-corporation'
import { Route as stocksNikeIncImport } from './routes/(stocks)/nike-inc'
import { Route as stocksBerkshireHathawayIncImport } from './routes/(stocks)/berkshire-hathaway-inc'
import { Route as stocksAppleIncImport } from './routes/(stocks)/apple-inc'
import { Route as AuthedDashboardIndexImport } from './routes/_authed/dashboard.index'
import { Route as AuthedDashboardUsersImport } from './routes/_authed/dashboard.users'
import { Route as AuthedDashboardInvoicesImport } from './routes/_authed/dashboard.invoices'
import { Route as AuthedDashboardUsersIndexImport } from './routes/_authed/dashboard.users.index'
import { Route as AuthedDashboardInvoicesIndexImport } from './routes/_authed/dashboard.invoices.index'
import { Route as AuthedDashboardUsersUserImport } from './routes/_authed/dashboard.users.user'
import { Route as AuthedDashboardInvoicesInvoiceIdImport } from './routes/_authed/dashboard.invoices.$invoiceId'

// Create/Update Routes

const DeferredDataRoute = DeferredDataImport.update({
  id: '/deferred-data',
  path: '/deferred-data',
  getParentRoute: () => rootRoute,
} as any)

const ContactUsRoute = ContactUsImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRoute,
} as any)

const AboutUsRoute = AboutUsImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutLayoutBRoute = LayoutLayoutBImport.update({
  id: '/layout-b',
  path: '/layout-b',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLayoutARoute = LayoutLayoutAImport.update({
  id: '/layout-a',
  path: '/layout-a',
  getParentRoute: () => LayoutRoute,
} as any)

const AuthedDashboardRoute = AuthedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const stocksStarbucksCorporationRoute = stocksStarbucksCorporationImport.update(
  {
    id: '/(stocks)/starbucks-corporation',
    path: '/starbucks-corporation',
    getParentRoute: () => rootRoute,
  } as any,
)

const stocksNikeIncRoute = stocksNikeIncImport.update({
  id: '/(stocks)/nike-inc',
  path: '/nike-inc',
  getParentRoute: () => rootRoute,
} as any)

const stocksBerkshireHathawayIncRoute = stocksBerkshireHathawayIncImport.update(
  {
    id: '/(stocks)/berkshire-hathaway-inc',
    path: '/berkshire-hathaway-inc',
    getParentRoute: () => rootRoute,
  } as any,
)

const stocksAppleIncRoute = stocksAppleIncImport.update({
  id: '/(stocks)/apple-inc',
  path: '/apple-inc',
  getParentRoute: () => rootRoute,
} as any)

const AuthedDashboardIndexRoute = AuthedDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

const AuthedDashboardUsersRoute = AuthedDashboardUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

const AuthedDashboardInvoicesRoute = AuthedDashboardInvoicesImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedDashboardRoute,
} as any)

const AuthedDashboardUsersIndexRoute = AuthedDashboardUsersIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDashboardUsersRoute,
} as any)

const AuthedDashboardInvoicesIndexRoute =
  AuthedDashboardInvoicesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedDashboardInvoicesRoute,
  } as any)

const AuthedDashboardUsersUserRoute = AuthedDashboardUsersUserImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthedDashboardUsersRoute,
} as any)

const AuthedDashboardInvoicesInvoiceIdRoute =
  AuthedDashboardInvoicesInvoiceIdImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => AuthedDashboardInvoicesRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsImport
      parentRoute: typeof rootRoute
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsImport
      parentRoute: typeof rootRoute
    }
    '/deferred-data': {
      id: '/deferred-data'
      path: '/deferred-data'
      fullPath: '/deferred-data'
      preLoaderRoute: typeof DeferredDataImport
      parentRoute: typeof rootRoute
    }
    '/(stocks)/apple-inc': {
      id: '/(stocks)/apple-inc'
      path: '/apple-inc'
      fullPath: '/apple-inc'
      preLoaderRoute: typeof stocksAppleIncImport
      parentRoute: typeof rootRoute
    }
    '/(stocks)/berkshire-hathaway-inc': {
      id: '/(stocks)/berkshire-hathaway-inc'
      path: '/berkshire-hathaway-inc'
      fullPath: '/berkshire-hathaway-inc'
      preLoaderRoute: typeof stocksBerkshireHathawayIncImport
      parentRoute: typeof rootRoute
    }
    '/(stocks)/nike-inc': {
      id: '/(stocks)/nike-inc'
      path: '/nike-inc'
      fullPath: '/nike-inc'
      preLoaderRoute: typeof stocksNikeIncImport
      parentRoute: typeof rootRoute
    }
    '/(stocks)/starbucks-corporation': {
      id: '/(stocks)/starbucks-corporation'
      path: '/starbucks-corporation'
      fullPath: '/starbucks-corporation'
      preLoaderRoute: typeof stocksStarbucksCorporationImport
      parentRoute: typeof rootRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardImport
      parentRoute: typeof AuthedImport
    }
    '/_layout/layout-a': {
      id: '/_layout/layout-a'
      path: '/layout-a'
      fullPath: '/layout-a'
      preLoaderRoute: typeof LayoutLayoutAImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/layout-b': {
      id: '/_layout/layout-b'
      path: '/layout-b'
      fullPath: '/layout-b'
      preLoaderRoute: typeof LayoutLayoutBImport
      parentRoute: typeof LayoutImport
    }
    '/_authed/dashboard/invoices': {
      id: '/_authed/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof AuthedDashboardInvoicesImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/users': {
      id: '/_authed/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthedDashboardUsersImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedDashboardIndexImport
      parentRoute: typeof AuthedDashboardImport
    }
    '/_authed/dashboard/invoices/$invoiceId': {
      id: '/_authed/dashboard/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/dashboard/invoices/$invoiceId'
      preLoaderRoute: typeof AuthedDashboardInvoicesInvoiceIdImport
      parentRoute: typeof AuthedDashboardInvoicesImport
    }
    '/_authed/dashboard/users/user': {
      id: '/_authed/dashboard/users/user'
      path: '/user'
      fullPath: '/dashboard/users/user'
      preLoaderRoute: typeof AuthedDashboardUsersUserImport
      parentRoute: typeof AuthedDashboardUsersImport
    }
    '/_authed/dashboard/invoices/': {
      id: '/_authed/dashboard/invoices/'
      path: '/'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof AuthedDashboardInvoicesIndexImport
      parentRoute: typeof AuthedDashboardInvoicesImport
    }
    '/_authed/dashboard/users/': {
      id: '/_authed/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof AuthedDashboardUsersIndexImport
      parentRoute: typeof AuthedDashboardUsersImport
    }
  }
}

// Create and export the route tree

interface AuthedDashboardInvoicesRouteChildren {
  AuthedDashboardInvoicesInvoiceIdRoute: typeof AuthedDashboardInvoicesInvoiceIdRoute
  AuthedDashboardInvoicesIndexRoute: typeof AuthedDashboardInvoicesIndexRoute
}

const AuthedDashboardInvoicesRouteChildren: AuthedDashboardInvoicesRouteChildren =
  {
    AuthedDashboardInvoicesInvoiceIdRoute:
      AuthedDashboardInvoicesInvoiceIdRoute,
    AuthedDashboardInvoicesIndexRoute: AuthedDashboardInvoicesIndexRoute,
  }

const AuthedDashboardInvoicesRouteWithChildren =
  AuthedDashboardInvoicesRoute._addFileChildren(
    AuthedDashboardInvoicesRouteChildren,
  )

interface AuthedDashboardUsersRouteChildren {
  AuthedDashboardUsersUserRoute: typeof AuthedDashboardUsersUserRoute
  AuthedDashboardUsersIndexRoute: typeof AuthedDashboardUsersIndexRoute
}

const AuthedDashboardUsersRouteChildren: AuthedDashboardUsersRouteChildren = {
  AuthedDashboardUsersUserRoute: AuthedDashboardUsersUserRoute,
  AuthedDashboardUsersIndexRoute: AuthedDashboardUsersIndexRoute,
}

const AuthedDashboardUsersRouteWithChildren =
  AuthedDashboardUsersRoute._addFileChildren(AuthedDashboardUsersRouteChildren)

interface AuthedDashboardRouteChildren {
  AuthedDashboardInvoicesRoute: typeof AuthedDashboardInvoicesRouteWithChildren
  AuthedDashboardUsersRoute: typeof AuthedDashboardUsersRouteWithChildren
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardInvoicesRoute: AuthedDashboardInvoicesRouteWithChildren,
  AuthedDashboardUsersRoute: AuthedDashboardUsersRouteWithChildren,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface LayoutRouteChildren {
  LayoutLayoutARoute: typeof LayoutLayoutARoute
  LayoutLayoutBRoute: typeof LayoutLayoutBRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLayoutARoute: LayoutLayoutARoute,
  LayoutLayoutBRoute: LayoutLayoutBRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/deferred-data': typeof DeferredDataRoute
  '/apple-inc': typeof stocksAppleIncRoute
  '/berkshire-hathaway-inc': typeof stocksBerkshireHathawayIncRoute
  '/nike-inc': typeof stocksNikeIncRoute
  '/starbucks-corporation': typeof stocksStarbucksCorporationRoute
  '/dashboard': typeof AuthedDashboardRouteWithChildren
  '/layout-a': typeof LayoutLayoutARoute
  '/layout-b': typeof LayoutLayoutBRoute
  '/dashboard/invoices': typeof AuthedDashboardInvoicesRouteWithChildren
  '/dashboard/users': typeof AuthedDashboardUsersRouteWithChildren
  '/dashboard/': typeof AuthedDashboardIndexRoute
  '/dashboard/invoices/$invoiceId': typeof AuthedDashboardInvoicesInvoiceIdRoute
  '/dashboard/users/user': typeof AuthedDashboardUsersUserRoute
  '/dashboard/invoices/': typeof AuthedDashboardInvoicesIndexRoute
  '/dashboard/users/': typeof AuthedDashboardUsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/deferred-data': typeof DeferredDataRoute
  '/apple-inc': typeof stocksAppleIncRoute
  '/berkshire-hathaway-inc': typeof stocksBerkshireHathawayIncRoute
  '/nike-inc': typeof stocksNikeIncRoute
  '/starbucks-corporation': typeof stocksStarbucksCorporationRoute
  '/layout-a': typeof LayoutLayoutARoute
  '/layout-b': typeof LayoutLayoutBRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/invoices/$invoiceId': typeof AuthedDashboardInvoicesInvoiceIdRoute
  '/dashboard/users/user': typeof AuthedDashboardUsersUserRoute
  '/dashboard/invoices': typeof AuthedDashboardInvoicesIndexRoute
  '/dashboard/users': typeof AuthedDashboardUsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_layout': typeof LayoutRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/deferred-data': typeof DeferredDataRoute
  '/(stocks)/apple-inc': typeof stocksAppleIncRoute
  '/(stocks)/berkshire-hathaway-inc': typeof stocksBerkshireHathawayIncRoute
  '/(stocks)/nike-inc': typeof stocksNikeIncRoute
  '/(stocks)/starbucks-corporation': typeof stocksStarbucksCorporationRoute
  '/_authed/dashboard': typeof AuthedDashboardRouteWithChildren
  '/_layout/layout-a': typeof LayoutLayoutARoute
  '/_layout/layout-b': typeof LayoutLayoutBRoute
  '/_authed/dashboard/invoices': typeof AuthedDashboardInvoicesRouteWithChildren
  '/_authed/dashboard/users': typeof AuthedDashboardUsersRouteWithChildren
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/invoices/$invoiceId': typeof AuthedDashboardInvoicesInvoiceIdRoute
  '/_authed/dashboard/users/user': typeof AuthedDashboardUsersUserRoute
  '/_authed/dashboard/invoices/': typeof AuthedDashboardInvoicesIndexRoute
  '/_authed/dashboard/users/': typeof AuthedDashboardUsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about-us'
    | '/contact-us'
    | '/deferred-data'
    | '/apple-inc'
    | '/berkshire-hathaway-inc'
    | '/nike-inc'
    | '/starbucks-corporation'
    | '/dashboard'
    | '/layout-a'
    | '/layout-b'
    | '/dashboard/invoices'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/users/user'
    | '/dashboard/invoices/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about-us'
    | '/contact-us'
    | '/deferred-data'
    | '/apple-inc'
    | '/berkshire-hathaway-inc'
    | '/nike-inc'
    | '/starbucks-corporation'
    | '/layout-a'
    | '/layout-b'
    | '/dashboard'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/users/user'
    | '/dashboard/invoices'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_layout'
    | '/about-us'
    | '/contact-us'
    | '/deferred-data'
    | '/(stocks)/apple-inc'
    | '/(stocks)/berkshire-hathaway-inc'
    | '/(stocks)/nike-inc'
    | '/(stocks)/starbucks-corporation'
    | '/_authed/dashboard'
    | '/_layout/layout-a'
    | '/_layout/layout-b'
    | '/_authed/dashboard/invoices'
    | '/_authed/dashboard/users'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/invoices/$invoiceId'
    | '/_authed/dashboard/users/user'
    | '/_authed/dashboard/invoices/'
    | '/_authed/dashboard/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  DeferredDataRoute: typeof DeferredDataRoute
  stocksAppleIncRoute: typeof stocksAppleIncRoute
  stocksBerkshireHathawayIncRoute: typeof stocksBerkshireHathawayIncRoute
  stocksNikeIncRoute: typeof stocksNikeIncRoute
  stocksStarbucksCorporationRoute: typeof stocksStarbucksCorporationRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LayoutRoute: LayoutRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  DeferredDataRoute: DeferredDataRoute,
  stocksAppleIncRoute: stocksAppleIncRoute,
  stocksBerkshireHathawayIncRoute: stocksBerkshireHathawayIncRoute,
  stocksNikeIncRoute: stocksNikeIncRoute,
  stocksStarbucksCorporationRoute: stocksStarbucksCorporationRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/_layout",
        "/about-us",
        "/contact-us",
        "/deferred-data",
        "/(stocks)/apple-inc",
        "/(stocks)/berkshire-hathaway-inc",
        "/(stocks)/nike-inc",
        "/(stocks)/starbucks-corporation"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/dashboard"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/layout-a",
        "/_layout/layout-b"
      ]
    },
    "/about-us": {
      "filePath": "about-us.tsx"
    },
    "/contact-us": {
      "filePath": "contact-us.tsx"
    },
    "/deferred-data": {
      "filePath": "deferred-data.tsx"
    },
    "/(stocks)/apple-inc": {
      "filePath": "(stocks)/apple-inc.tsx"
    },
    "/(stocks)/berkshire-hathaway-inc": {
      "filePath": "(stocks)/berkshire-hathaway-inc.tsx"
    },
    "/(stocks)/nike-inc": {
      "filePath": "(stocks)/nike-inc.tsx"
    },
    "/(stocks)/starbucks-corporation": {
      "filePath": "(stocks)/starbucks-corporation.tsx"
    },
    "/_authed/dashboard": {
      "filePath": "_authed/dashboard.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/dashboard/invoices",
        "/_authed/dashboard/users",
        "/_authed/dashboard/"
      ]
    },
    "/_layout/layout-a": {
      "filePath": "_layout.layout-a.tsx",
      "parent": "/_layout"
    },
    "/_layout/layout-b": {
      "filePath": "_layout.layout-b.tsx",
      "parent": "/_layout"
    },
    "/_authed/dashboard/invoices": {
      "filePath": "_authed/dashboard.invoices.tsx",
      "parent": "/_authed/dashboard",
      "children": [
        "/_authed/dashboard/invoices/$invoiceId",
        "/_authed/dashboard/invoices/"
      ]
    },
    "/_authed/dashboard/users": {
      "filePath": "_authed/dashboard.users.tsx",
      "parent": "/_authed/dashboard",
      "children": [
        "/_authed/dashboard/users/user",
        "/_authed/dashboard/users/"
      ]
    },
    "/_authed/dashboard/": {
      "filePath": "_authed/dashboard.index.tsx",
      "parent": "/_authed/dashboard"
    },
    "/_authed/dashboard/invoices/$invoiceId": {
      "filePath": "_authed/dashboard.invoices.$invoiceId.tsx",
      "parent": "/_authed/dashboard/invoices"
    },
    "/_authed/dashboard/users/user": {
      "filePath": "_authed/dashboard.users.user.tsx",
      "parent": "/_authed/dashboard/users"
    },
    "/_authed/dashboard/invoices/": {
      "filePath": "_authed/dashboard.invoices.index.tsx",
      "parent": "/_authed/dashboard/invoices"
    },
    "/_authed/dashboard/users/": {
      "filePath": "_authed/dashboard.users.index.tsx",
      "parent": "/_authed/dashboard/users"
    }
  }
}
ROUTE_MANIFEST_END */
