/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DeferredDataImport } from './routes/deferred-data'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as ContactUsImport } from './routes/contact-us'
import { Route as AboutUsImport } from './routes/about-us'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard.index'
import { Route as DashboardUsersImport } from './routes/dashboard.users'
import { Route as DashboardInvoicesImport } from './routes/dashboard.invoices'
import { Route as LayoutLayoutBImport } from './routes/_layout.layout-b'
import { Route as LayoutLayoutAImport } from './routes/_layout.layout-a'
import { Route as stocksStarbucksCorporationImport } from './routes/(stocks)/starbucks-corporation'
import { Route as stocksNikeIncImport } from './routes/(stocks)/nike-inc'
import { Route as stocksBerkshireHathawayIncImport } from './routes/(stocks)/berkshire-hathaway-inc'
import { Route as stocksAppleIncImport } from './routes/(stocks)/apple-inc'
import { Route as DashboardUsersIndexImport } from './routes/dashboard.users.index'
import { Route as DashboardInvoicesIndexImport } from './routes/dashboard.invoices.index'
import { Route as DashboardUsersUserImport } from './routes/dashboard.users.user'
import { Route as DashboardInvoicesInvoiceIdImport } from './routes/dashboard.invoices.$invoiceId'

// Create Virtual Routes

const ExpensiveIndexLazyImport = createFileRoute('/expensive/')()

// Create/Update Routes

const DeferredDataRoute = DeferredDataImport.update({
  path: '/deferred-data',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ContactUsRoute = ContactUsImport.update({
  path: '/contact-us',
  getParentRoute: () => rootRoute,
} as any)

const AboutUsRoute = AboutUsImport.update({
  path: '/about-us',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ExpensiveIndexLazyRoute = ExpensiveIndexLazyImport.update({
  path: '/expensive/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/expensive/index.lazy').then((d) => d.Route),
)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardUsersRoute = DashboardUsersImport.update({
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardInvoicesRoute = DashboardInvoicesImport.update({
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)

const LayoutLayoutBRoute = LayoutLayoutBImport.update({
  path: '/layout-b',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLayoutARoute = LayoutLayoutAImport.update({
  path: '/layout-a',
  getParentRoute: () => LayoutRoute,
} as any)

const stocksStarbucksCorporationRoute = stocksStarbucksCorporationImport.update(
  {
    path: '/starbucks-corporation',
    getParentRoute: () => rootRoute,
  } as any,
)

const stocksNikeIncRoute = stocksNikeIncImport.update({
  path: '/nike-inc',
  getParentRoute: () => rootRoute,
} as any)

const stocksBerkshireHathawayIncRoute = stocksBerkshireHathawayIncImport.update(
  {
    path: '/berkshire-hathaway-inc',
    getParentRoute: () => rootRoute,
  } as any,
)

const stocksAppleIncRoute = stocksAppleIncImport.update({
  path: '/apple-inc',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUsersIndexRoute = DashboardUsersIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardUsersRoute,
} as any)

const DashboardInvoicesIndexRoute = DashboardInvoicesIndexImport.update({
  path: '/',
  getParentRoute: () => DashboardInvoicesRoute,
} as any)

const DashboardUsersUserRoute = DashboardUsersUserImport.update({
  path: '/user',
  getParentRoute: () => DashboardUsersRoute,
} as any)

const DashboardInvoicesInvoiceIdRoute = DashboardInvoicesInvoiceIdImport.update(
  {
    path: '/$invoiceId',
    getParentRoute: () => DashboardInvoicesRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsImport
      parentRoute: typeof rootRoute
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/deferred-data': {
      id: '/deferred-data'
      path: '/deferred-data'
      fullPath: '/deferred-data'
      preLoaderRoute: typeof DeferredDataImport
      parentRoute: typeof rootRoute
    }
    '/(stocks)/apple-inc': {
      id: '/apple-inc'
      path: '/apple-inc'
      fullPath: '/apple-inc'
      preLoaderRoute: typeof stocksAppleIncImport
      parentRoute: typeof rootRoute
    }
    '/(stocks)/berkshire-hathaway-inc': {
      id: '/berkshire-hathaway-inc'
      path: '/berkshire-hathaway-inc'
      fullPath: '/berkshire-hathaway-inc'
      preLoaderRoute: typeof stocksBerkshireHathawayIncImport
      parentRoute: typeof rootRoute
    }
    '/(stocks)/nike-inc': {
      id: '/nike-inc'
      path: '/nike-inc'
      fullPath: '/nike-inc'
      preLoaderRoute: typeof stocksNikeIncImport
      parentRoute: typeof rootRoute
    }
    '/(stocks)/starbucks-corporation': {
      id: '/starbucks-corporation'
      path: '/starbucks-corporation'
      fullPath: '/starbucks-corporation'
      preLoaderRoute: typeof stocksStarbucksCorporationImport
      parentRoute: typeof rootRoute
    }
    '/_layout/layout-a': {
      id: '/_layout/layout-a'
      path: '/layout-a'
      fullPath: '/layout-a'
      preLoaderRoute: typeof LayoutLayoutAImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/layout-b': {
      id: '/_layout/layout-b'
      path: '/layout-b'
      fullPath: '/layout-b'
      preLoaderRoute: typeof LayoutLayoutBImport
      parentRoute: typeof LayoutImport
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/expensive/': {
      id: '/expensive/'
      path: '/expensive'
      fullPath: '/expensive'
      preLoaderRoute: typeof ExpensiveIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/invoices/$invoiceId': {
      id: '/dashboard/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/dashboard/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardInvoicesInvoiceIdImport
      parentRoute: typeof DashboardInvoicesImport
    }
    '/dashboard/users/user': {
      id: '/dashboard/users/user'
      path: '/user'
      fullPath: '/dashboard/users/user'
      preLoaderRoute: typeof DashboardUsersUserImport
      parentRoute: typeof DashboardUsersImport
    }
    '/dashboard/invoices/': {
      id: '/dashboard/invoices/'
      path: '/'
      fullPath: '/dashboard/invoices/'
      preLoaderRoute: typeof DashboardInvoicesIndexImport
      parentRoute: typeof DashboardInvoicesImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexImport
      parentRoute: typeof DashboardUsersImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutLayoutARoute: typeof LayoutLayoutARoute
  LayoutLayoutBRoute: typeof LayoutLayoutBRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLayoutARoute: LayoutLayoutARoute,
  LayoutLayoutBRoute: LayoutLayoutBRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface DashboardInvoicesRouteChildren {
  DashboardInvoicesInvoiceIdRoute: typeof DashboardInvoicesInvoiceIdRoute
  DashboardInvoicesIndexRoute: typeof DashboardInvoicesIndexRoute
}

const DashboardInvoicesRouteChildren: DashboardInvoicesRouteChildren = {
  DashboardInvoicesInvoiceIdRoute: DashboardInvoicesInvoiceIdRoute,
  DashboardInvoicesIndexRoute: DashboardInvoicesIndexRoute,
}

const DashboardInvoicesRouteWithChildren =
  DashboardInvoicesRoute._addFileChildren(DashboardInvoicesRouteChildren)

interface DashboardUsersRouteChildren {
  DashboardUsersUserRoute: typeof DashboardUsersUserRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardUsersRouteChildren: DashboardUsersRouteChildren = {
  DashboardUsersUserRoute: DashboardUsersUserRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardUsersRouteWithChildren = DashboardUsersRoute._addFileChildren(
  DashboardUsersRouteChildren,
)

interface DashboardRouteChildren {
  DashboardInvoicesRoute: typeof DashboardInvoicesRouteWithChildren
  DashboardUsersRoute: typeof DashboardUsersRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInvoicesRoute: DashboardInvoicesRouteWithChildren,
  DashboardUsersRoute: DashboardUsersRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deferred-data': typeof DeferredDataRoute
  '/apple-inc': typeof stocksAppleIncRoute
  '/berkshire-hathaway-inc': typeof stocksBerkshireHathawayIncRoute
  '/nike-inc': typeof stocksNikeIncRoute
  '/starbucks-corporation': typeof stocksStarbucksCorporationRoute
  '/layout-a': typeof LayoutLayoutARoute
  '/layout-b': typeof LayoutLayoutBRoute
  '/dashboard/invoices': typeof DashboardInvoicesRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/expensive': typeof ExpensiveIndexLazyRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/users/user': typeof DashboardUsersUserRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/deferred-data': typeof DeferredDataRoute
  '/apple-inc': typeof stocksAppleIncRoute
  '/berkshire-hathaway-inc': typeof stocksBerkshireHathawayIncRoute
  '/nike-inc': typeof stocksNikeIncRoute
  '/starbucks-corporation': typeof stocksStarbucksCorporationRoute
  '/layout-a': typeof LayoutLayoutARoute
  '/layout-b': typeof LayoutLayoutBRoute
  '/dashboard': typeof DashboardIndexRoute
  '/expensive': typeof ExpensiveIndexLazyRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/users/user': typeof DashboardUsersUserRoute
  '/dashboard/invoices': typeof DashboardInvoicesIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/about-us': typeof AboutUsRoute
  '/contact-us': typeof ContactUsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deferred-data': typeof DeferredDataRoute
  '/apple-inc': typeof stocksAppleIncRoute
  '/berkshire-hathaway-inc': typeof stocksBerkshireHathawayIncRoute
  '/nike-inc': typeof stocksNikeIncRoute
  '/starbucks-corporation': typeof stocksStarbucksCorporationRoute
  '/_layout/layout-a': typeof LayoutLayoutARoute
  '/_layout/layout-b': typeof LayoutLayoutBRoute
  '/dashboard/invoices': typeof DashboardInvoicesRouteWithChildren
  '/dashboard/users': typeof DashboardUsersRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/expensive/': typeof ExpensiveIndexLazyRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/users/user': typeof DashboardUsersUserRoute
  '/dashboard/invoices/': typeof DashboardInvoicesIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about-us'
    | '/contact-us'
    | '/dashboard'
    | '/deferred-data'
    | '/apple-inc'
    | '/berkshire-hathaway-inc'
    | '/nike-inc'
    | '/starbucks-corporation'
    | '/layout-a'
    | '/layout-b'
    | '/dashboard/invoices'
    | '/dashboard/users'
    | '/dashboard/'
    | '/expensive'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/users/user'
    | '/dashboard/invoices/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about-us'
    | '/contact-us'
    | '/deferred-data'
    | '/apple-inc'
    | '/berkshire-hathaway-inc'
    | '/nike-inc'
    | '/starbucks-corporation'
    | '/layout-a'
    | '/layout-b'
    | '/dashboard'
    | '/expensive'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/users/user'
    | '/dashboard/invoices'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/about-us'
    | '/contact-us'
    | '/dashboard'
    | '/deferred-data'
    | '/apple-inc'
    | '/berkshire-hathaway-inc'
    | '/nike-inc'
    | '/starbucks-corporation'
    | '/_layout/layout-a'
    | '/_layout/layout-b'
    | '/dashboard/invoices'
    | '/dashboard/users'
    | '/dashboard/'
    | '/expensive/'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/users/user'
    | '/dashboard/invoices/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  AboutUsRoute: typeof AboutUsRoute
  ContactUsRoute: typeof ContactUsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeferredDataRoute: typeof DeferredDataRoute
  stocksAppleIncRoute: typeof stocksAppleIncRoute
  stocksBerkshireHathawayIncRoute: typeof stocksBerkshireHathawayIncRoute
  stocksNikeIncRoute: typeof stocksNikeIncRoute
  stocksStarbucksCorporationRoute: typeof stocksStarbucksCorporationRoute
  ExpensiveIndexLazyRoute: typeof ExpensiveIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  AboutUsRoute: AboutUsRoute,
  ContactUsRoute: ContactUsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeferredDataRoute: DeferredDataRoute,
  stocksAppleIncRoute: stocksAppleIncRoute,
  stocksBerkshireHathawayIncRoute: stocksBerkshireHathawayIncRoute,
  stocksNikeIncRoute: stocksNikeIncRoute,
  stocksStarbucksCorporationRoute: stocksStarbucksCorporationRoute,
  ExpensiveIndexLazyRoute: ExpensiveIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/about-us",
        "/contact-us",
        "/dashboard",
        "/deferred-data",
        "/apple-inc",
        "/berkshire-hathaway-inc",
        "/nike-inc",
        "/starbucks-corporation",
        "/expensive/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/layout-a",
        "/_layout/layout-b"
      ]
    },
    "/about-us": {
      "filePath": "about-us.tsx"
    },
    "/contact-us": {
      "filePath": "contact-us.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/invoices",
        "/dashboard/users",
        "/dashboard/"
      ]
    },
    "/deferred-data": {
      "filePath": "deferred-data.tsx"
    },
    "/apple-inc": {
      "filePath": "(stocks)/apple-inc.tsx"
    },
    "/berkshire-hathaway-inc": {
      "filePath": "(stocks)/berkshire-hathaway-inc.tsx"
    },
    "/nike-inc": {
      "filePath": "(stocks)/nike-inc.tsx"
    },
    "/starbucks-corporation": {
      "filePath": "(stocks)/starbucks-corporation.tsx"
    },
    "/_layout/layout-a": {
      "filePath": "_layout.layout-a.tsx",
      "parent": "/_layout"
    },
    "/_layout/layout-b": {
      "filePath": "_layout.layout-b.tsx",
      "parent": "/_layout"
    },
    "/dashboard/invoices": {
      "filePath": "dashboard.invoices.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/invoices/$invoiceId",
        "/dashboard/invoices/"
      ]
    },
    "/dashboard/users": {
      "filePath": "dashboard.users.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/users/user",
        "/dashboard/users/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard.index.tsx",
      "parent": "/dashboard"
    },
    "/expensive/": {
      "filePath": "expensive/index.lazy.tsx"
    },
    "/dashboard/invoices/$invoiceId": {
      "filePath": "dashboard.invoices.$invoiceId.tsx",
      "parent": "/dashboard/invoices"
    },
    "/dashboard/users/user": {
      "filePath": "dashboard.users.user.tsx",
      "parent": "/dashboard/users"
    },
    "/dashboard/invoices/": {
      "filePath": "dashboard.invoices.index.tsx",
      "parent": "/dashboard/invoices"
    },
    "/dashboard/users/": {
      "filePath": "dashboard.users.index.tsx",
      "parent": "/dashboard/users"
    }
  }
}
ROUTE_MANIFEST_END */
